# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: False

runner: "episode" # parallel修改为episode

buffer_size: 8 # buffer最大存储的episode数量
batch_size_run: 1 #　对应runner，从8修改为1， 执行episode runner需要设置为1
batch_size: 1  # 从buffer size 中选择的多少episode来训练

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 100  # 指的是训练多少step来更新一次，一般和一个回合的step数量一样

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "coma"
