agent: rnn
batch_size: 32
batch_size_run: 1
buffer_cpu_only: true
buffer_size: 32
cal_max_expectation_tasks: true
checkpoint_path: /home/csyi/pymarl/src/results/models/qmix__2020-03-14_16-41-18
critic_lr: 0.0005
env: ec
env_args: {}
evaluate: false
gamma: 0.99
grad_norm_clip: 10
label: default_label
learner_log_interval: 100
load_step: 0
local_results_path: results
log_interval: 100
lr: 0.0005
mac: basic_mac
obs_agent_id: true
obs_last_action: true
optim_alpha: 0.99
optim_eps: 1.0e-05
repeat_id: 1
rnn_hidden_dim: 64
runner: episode
runner_log_interval: 100
save_model: true
save_model_interval: 40000
save_replay: false
t_max: 3000
test_greedy: true
test_interval: 1000
test_nepisode: 1
use_cuda: true
use_tensorboard: true
