# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
#控制测试 run的次数，为test_nepisode//batch_size_run
test_nepisode: 1 # Number of episodes to test for
#控制每隔多少次就test一次，一般为step的倍数，可以为1倍
test_interval: 1000 # Test after {} timesteps have passed
#选择动作的时候是否有随即选
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0

##控制多少step输出log信息，一般为step的一倍
log_interval: 100 # Log summary of stats after every {} timesteps
#控制对episoderunner输出log信息的频率，一般为step的倍数
runner_log_interval: 100 # Log runner stats (not test stats) every {} timesteps
#控制comalearner输出信息的频率，一般为step整数倍
learner_log_interval: 100 # Log training stats every {} timesteps
t_max: 100000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: False # Save the models to disk
#控制每隔多少step来保存模型参数，一般为step整数倍
save_model_interval: 10000 # Save models after this many timesteps
#加载模型的路径
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
